### ISSUE TITLE
`TypeError: Cannot read property 'trim' of undefined` at `parser.js:21:62`

### ISSUE THREAD

**Issue by klesun-misc** [OllieTerrance/SMParse#1]
Hello. Not sure if it's a malformed `.sm` file or an issue with the code. Just in case, posting here

 the chart which causes parser to fail:

[HUNTING FOR YOU.sm](https://github.com/Terrance/SMParse/files/6535126/HUNTING.FOR.YOU.sm.txt)

```
DancingStage%20SuperNOVA.zip
Hunting For You
Main script failed TypeError: Cannot read property 'trim' of undefined
    at new SMParse (/home/klesun/gits/klesun-productions.com/node_modules/SMParse/SMParse/res/js/parser.js:21:62)
    at collectSongIndex (/home/klesun/gits/klesun-productions.com/entry/ddr-songs-browser/scripts/collect_songs_index.cjs:36:20)
    at async Promise.all (index 34)
    at async collectSubdirIndex (/home/klesun/gits/klesun-productions.com/entry/ddr-songs-browser/scripts/collect_songs_index.cjs:93:19)
    at async Promise.all (index 0)
    at async collectPackIndex (/home/klesun/gits/klesun-productions.com/entry/ddr-songs-browser/scripts/collect_songs_index.cjs:113:24)
    at async main (/home/klesun/gits/klesun-productions.com/entry/ddr-songs-browser/scripts/collect_songs_index.cjs:135:27)
```

**Comment by Terrance** [comment]
This chart lacks an author credit:

```
#NOTES:
     dance-single:
     // (put an author name here)
     Hard:
     7:
     0.422,0.084,0.363,0.139,0.208:
  // measure 1
...
```

Adding one should get you around this (in ArrowVortex it's the _Step artist_ field in _Chart Properties_).  Seems that the field is just omitted in the SM note data when unset, so there's an optional field that need handling here.
